// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2020-04-15 20:27:29.719672 +0800 CST m=+0.081516101

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "获取token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回token",
                        "schema": {
                            "$ref": "#/definitions/api.AuthRes"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.AuthRes"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.LoginRes"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/v1.LoginRes"
                        }
                    }
                }
            }
        },
        "/user": {
            "put": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "修改密码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "旧密码",
                        "name": "old",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "新密码",
                        "name": "new",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/v1.UserRes"
                        }
                    },
                    "400": {
                        "description": "失败",
                        "schema": {
                            "$ref": "#/definitions/v1.UserRes"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.UserRes"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/v1.UserRes"
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "删除用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功 code = 200",
                        "schema": {
                            "$ref": "#/definitions/v1.UserRes"
                        }
                    }
                }
            }
        },
        "/v1/data": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数据"
                ],
                "summary": "获取数据点数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "pointID",
                        "name": "pID",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "从机地址",
                        "name": "slaverIndex",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "devID",
                        "name": "devID",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "开始时间(unix)",
                        "name": "start",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "结束时间(unix)",
                        "name": "end",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "$ref": "#/definitions/v1.PointDataRes"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数据"
                ],
                "summary": "删除数据点下的数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "pointID",
                        "name": "pID",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "从机地址",
                        "name": "slaverIndex",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "devID",
                        "name": "devID",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/device": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "设备"
                ],
                "summary": "获取用户设备",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回设备",
                        "schema": {
                            "$ref": "#/definitions/v1.DeviceReq"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "设备存在",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "设备"
                ],
                "summary": "更新设备",
                "parameters": [
                    {
                        "description": "设备",
                        "name": "device",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.DeviceReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回设备",
                        "schema": {
                            "$ref": "#/definitions/models.Device"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "设备"
                ],
                "summary": "添加设备",
                "parameters": [
                    {
                        "description": "设备",
                        "name": "device",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.DeviceReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回设备",
                        "schema": {
                            "$ref": "#/definitions/models.Device"
                        }
                    },
                    "400": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "设备"
                ],
                "summary": "删除设备以及从机",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "设备ID",
                        "name": "deviceID",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/schedule": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "定时任务"
                ],
                "summary": "获取设备定时任务",
                "parameters": [
                    {
                        "type": "string",
                        "description": "添加定时任务",
                        "name": "devID",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回设备",
                        "schema": {
                            "$ref": "#/definitions/models.DeviceTask"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "定时任务"
                ],
                "summary": "更新并执行设备定时任务",
                "parameters": [
                    {
                        "description": "更新后的定时任务",
                        "name": "device",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.AddScheReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回定时任务",
                        "schema": {
                            "$ref": "#/definitions/models.DeviceTask"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "定时任务"
                ],
                "summary": "添加设备定时任务",
                "parameters": [
                    {
                        "description": "添加定时任务",
                        "name": "device",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.AddScheReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回设备",
                        "schema": {
                            "$ref": "#/definitions/models.DeviceTask"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "定时任务"
                ],
                "summary": "删除设备定时任务",
                "parameters": [
                    {
                        "type": "string",
                        "description": "设备的devID 16位",
                        "name": "devID",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/template": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模板"
                ],
                "summary": "获取用户模板",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回模板",
                        "schema": {
                            "$ref": "#/definitions/models.Template"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模板"
                ],
                "summary": "更新数据模板",
                "parameters": [
                    {
                        "description": "模板参数",
                        "name": "template",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.AddTempReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回模板",
                        "schema": {
                            "$ref": "#/definitions/models.Template"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "返回添加好的数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模板"
                ],
                "summary": "添加数据模板及其数据点",
                "parameters": [
                    {
                        "description": "数据模板",
                        "name": "template",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.AddTempReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回模板",
                        "schema": {
                            "$ref": "#/definitions/models.Template"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模板"
                ],
                "summary": "删除数据模板及其数据点",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "模板ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.AuthRes": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "string"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "models.DataPoint": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "dataType": {
                    "type": "integer"
                },
                "formula": {
                    "type": "string"
                },
                "frequency": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "templateID": {
                    "type": "integer"
                },
                "unit": {
                    "type": "string"
                }
            }
        },
        "models.Device": {
            "type": "object",
            "properties": {
                "addr": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "devID": {
                    "type": "string"
                },
                "deviceName": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "position": {
                    "type": "string"
                },
                "slavers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Slaver"
                    }
                },
                "status": {
                    "type": "boolean"
                },
                "updatedAt": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.DeviceTask": {
            "type": "object",
            "properties": {
                "devID": {
                    "type": "string"
                },
                "frequency": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Task"
                    }
                }
            }
        },
        "models.PointData": {
            "type": "object",
            "properties": {
                "cTime": {
                    "type": "integer"
                },
                "data": {
                    "type": "string"
                },
                "devID": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "pointID": {
                    "type": "integer"
                },
                "slaverIndex": {
                    "type": "string"
                }
            }
        },
        "models.Slaver": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "devID": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "slaverIndex": {
                    "type": "integer"
                },
                "slaverName": {
                    "type": "string"
                },
                "templateID": {
                    "type": "integer"
                },
                "templateName": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "models.Task": {
            "type": "object",
            "properties": {
                "deviceTaskID": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "pointID": {
                    "type": "integer"
                },
                "query": {
                    "type": "string"
                }
            }
        },
        "models.Template": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "dataPoints": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.DataPoint"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "templateName": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lastLogin": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "v1.AddScheReq": {
            "type": "object",
            "properties": {
                "devID": {
                    "type": "string"
                },
                "frequency": {
                    "type": "integer"
                },
                "tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.TaskReq"
                    }
                }
            }
        },
        "v1.AddTempReq": {
            "type": "object",
            "properties": {
                "dataPoints": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.TempDataPoint"
                    }
                },
                "templateName": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "v1.DeviceReq": {
            "type": "object",
            "properties": {
                "addr": {
                    "type": "string"
                },
                "devID": {
                    "type": "string"
                },
                "deviceName": {
                    "type": "string"
                },
                "position": {
                    "type": "string"
                },
                "slavers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.slaverTemp"
                    }
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "v1.LoginData": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user": {
                    "type": "object",
                    "$ref": "#/definitions/models.User"
                }
            }
        },
        "v1.LoginRes": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "object",
                    "$ref": "#/definitions/v1.LoginData"
                },
                "msg": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "v1.PointDataRes": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.PointData"
                    }
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "v1.TaskReq": {
            "type": "object",
            "properties": {
                "pointID": {
                    "type": "integer"
                },
                "query": {
                    "type": "string"
                }
            }
        },
        "v1.TempDataPoint": {
            "type": "object",
            "properties": {
                "dataType": {
                    "type": "integer"
                },
                "formula": {
                    "type": "string"
                },
                "frequency": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "unit": {
                    "type": "string"
                }
            }
        },
        "v1.UserRes": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "object",
                    "$ref": "#/definitions/models.User"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "v1.slaverTemp": {
            "type": "object",
            "properties": {
                "deviceID": {
                    "type": "integer"
                },
                "slaverIndex": {
                    "type": "integer"
                },
                "slaverName": {
                    "type": "string"
                },
                "templateID": {
                    "type": "integer"
                },
                "templateName": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "127.0.0.1:15001",
	BasePath:    "/api",
	Schemes:     []string{},
	Title:       "mserver API",
	Description: "加锁的API需要Authorization",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
